### ISSUE TITLE
remove the `proper` plugins from the build

### ISSUE THREAD

**Issue by benoitc** [ferd/backoff#20]
Each time I am trying to test my own code and fetch the backoff dependency it tries to compile proper which create 2 issues imo:

1) we have to fetch an unwanted dep
2) it triggers some warning:

```
/_build/default/plugins/proper/src/proper_typeserver.erl:553: Warning: erlang:get_stacktrace/0 used following a 'try' expression may stop working in a future release. (Use it inside 'try'.)
_build/default/plugins/proper/src/proper_typeserver.erl:556: Warning: erlang:get_stacktrace/0 used following a 'try' expression may stop working in a future release. (Use it inside 'try'.)
_build/default/plugins/proper/src/proper_typeserver.erl:553: Warning: erlang:get_stacktrace/0 used following a 'try' expression may stop working in a future release. (Use it inside 'try'.)
_build/default/plugins/proper/src/proper_typeserver.erl:556: Warning: erlang:get_stacktrace/0 used following a 'try' expression may stop working in a future release. (Use it inside 'try'.)
```

Woiuld it be possible to have this plugin only set by the users in its own config file?  For the second maybe also a newer version of proper is existing?

**Comment by ferd** [comment]
I could simply move the `proper` plugin to go in the `test` build; it would force to run `rebar3 as test proper` but that's probably acceptable.

**Comment by ferd** [comment]
Also the dep is fetched only as a plugin and should never be part of any release, in case that was a concern.

**Comment by benoitc** [comment]
@ferd would be fine yes I guess. I think the most important issue are the warnings also, not sure what can be done on it though.

**Comment by ferd** [comment]
Yeah nothing about warnings until a new release of proper is cut. The current one is two years old and that explains deprecation warnings.
